version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: aklciot/monitor
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  script:
    image: aklciot/mqtt-script
    build:
      context: .
      dockerfile: script-dockerfile
    command: python mqtt-monitor.py
    volumes:
      - .:/code
    #restart: always
    depends_on:
      - db
    #  - mqtt
    environment:
      AKLC_MQTT_CLIENT_ID: mqtt_monitor_home_test
      AKLC_MQTT_HOST: aws2.innovateauckland.nz
      AKLC_MQTT_USER: aklciot
      AKLC_MQTT_PASSWORD: iotiscool
      AKLC_TEST_DAILY: T
      AKLC_WEB_BASE_URL: http://localhost:8001

  #mqtt:
  #  image: eclipse-mosquitto
  #  ports:
  #    - "1883:1883"
  #nodered:
  #  image: nodered/node-red-docker
  #  ports:
  #    - "1880:1880"
  #  volumes:
  #    - nodered-data:/data

#networks:
volumes:
  postgres-data:
  #nodered-data:
